# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Converts CSV files located in _data to usable Markdown

on:
  # Runs on push to trainer
  push:
    branches: ["trainer"]

  # Allows manual run
  workflow_dispatch:

# Sets permissions
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Rename file 
        run: mv _data/*.csv Data/*.md
